/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ホームデータ取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ホームデータ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HomeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ログイン */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description ログイン成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ユーザー登録 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description 登録成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ログアウト */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ログアウト成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 現在のユーザー取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ユーザー情報 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user_profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** プロフィール取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description プロフィール情報 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserProfile"];
                    };
                };
                /** @description プロフィールが見つかりません */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** プロフィール作成 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserProfileRequest"];
                };
            };
            responses: {
                /** @description プロフィール作成成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserProfile"];
                    };
                };
                /** @description バリデーションエラー */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        /** プロフィール更新 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserProfileRequest"];
                };
            };
            responses: {
                /** @description プロフィール更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserProfile"];
                    };
                };
                /** @description バリデーションエラー */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            id: number;
            email: string;
            name: string;
            /** @enum {string} */
            role: "admin" | "user";
            /** Format: date-time */
            created_at: string;
        };
        UserProfile: {
            id: number;
            user_id: number;
            last_name: string;
            first_name: string;
            last_name_kana: string;
            first_name_kana: string;
            /** Format: date */
            birth_date?: string | null;
            /** @enum {string|null} */
            gender?: "male" | "female" | "other" | "prefer_not_to_say" | null;
            phone_number?: string | null;
            postal_code?: string | null;
            prefecture?: string | null;
            city?: string | null;
            address_line?: string | null;
            building?: string | null;
            emergency_contact_name?: string | null;
            emergency_contact_phone?: string | null;
            desired_job_type?: string | null;
            skills?: string | null;
            certifications?: string | null;
            years_of_experience?: number | null;
            desired_work_location?: string | null;
            /** @enum {string|null} */
            desired_employment_type?: "full_time" | "part_time" | "contract" | "temporary" | "freelance" | null;
            desired_hourly_rate?: number | null;
            profile_image_url?: string | null;
            self_introduction?: string | null;
            available_days?: string | null;
            transportation?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AuthTokens: {
            access_token: string;
            refresh_token: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        RegisterRequest: {
            user: {
                email: string;
                password: string;
                password_confirmation: string;
                name: string;
            };
        };
        UserProfileRequest: {
            user_profile: {
                last_name: string;
                first_name: string;
                last_name_kana: string;
                first_name_kana: string;
                /** Format: date */
                birth_date?: string | null;
                /** @enum {string|null} */
                gender?: "male" | "female" | "other" | "prefer_not_to_say" | null;
                phone_number?: string | null;
                postal_code?: string | null;
                prefecture?: string | null;
                city?: string | null;
                address_line?: string | null;
                building?: string | null;
                emergency_contact_name?: string | null;
                emergency_contact_phone?: string | null;
                desired_job_type?: string | null;
                skills?: string | null;
                certifications?: string | null;
                years_of_experience?: number | null;
                desired_work_location?: string | null;
                /** @enum {string|null} */
                desired_employment_type?: "full_time" | "part_time" | "contract" | "temporary" | "freelance" | null;
                desired_hourly_rate?: number | null;
                profile_image_url?: string | null;
                self_introduction?: string | null;
                available_days?: string | null;
                transportation?: string | null;
            };
        };
        AuthResponse: {
            /** @enum {string} */
            status: "success" | "error";
            message: string;
            data?: {
                user?: components["schemas"]["User"];
                tokens?: components["schemas"]["AuthTokens"];
            };
            errors?: string[];
        };
        MeResponse: {
            /** @enum {string} */
            status: "success" | "error";
            message?: string;
            data?: {
                user?: components["schemas"]["User"];
            };
        };
        HomeResponse: {
            message: string;
            status: string;
            data: {
                title: string;
                description: string;
                version: string;
            };
        };
        ErrorResponse: {
            errors?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;

// 型エイリアス - 使いやすくするためのヘルパー
export type User = components["schemas"]["User"];
export type UserProfile = components["schemas"]["UserProfile"];
export type AuthTokens = components["schemas"]["AuthTokens"];
export type LoginRequest = components["schemas"]["LoginRequest"];
export type RegisterRequest = components["schemas"]["RegisterRequest"];
export type UserProfileRequest = components["schemas"]["UserProfileRequest"];
export type AuthResponse = components["schemas"]["AuthResponse"];
export type MeResponse = components["schemas"]["MeResponse"];
export type HomeResponse = components["schemas"]["HomeResponse"];
export type ErrorResponse = components["schemas"]["ErrorResponse"];
